sudo: required
language: rust

# Dependencies of kcov, used by coverage
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

# run builds for all the trains (and more)
rust:
  - nightly
  - beta
  # check it compiles on the latest stable compiler
  - stable
  # Test for the minimum required version
  - 1.39.0

matrix:
  allow_failures:
    - rust: nightly

# the main build
script:
  - |
    rustc -vV &&
    cargo -vV &&
    cargo build -p iban_validate &&
    cargo test -p iban_validate &&
    cargo doc -p iban_validate &&
    cargo build --no-default-features -p iban_validate &&
    cargo test --no-default-features -p iban_validate &&
    cargo doc --no-default-features -p iban_validate &&
    cargo build --no-default-features --features serde -p iban_validate &&
    cargo test --no-default-features --features serde -p iban_validate &&
    cargo doc --no-default-features --features serde -p iban_validate &&
    cargo build --features serde -p iban_validate &&
    cargo test --features serde -p iban_validate &&
    cargo doc --features serde -p iban_validate

after_success:
  # measure code coverage and upload to coveralls.io
  - cargo coveralls
