environment:
  matrix:
    - channel: stable
      target: x86_64-pc-windows-msvc
    - channel: stable
      target: i686-pc-windows-msvc
    - channel: beta
      target: x86_64-pc-windows-msvc
    - channel: beta
      target: i686-pc-windows-msvc
    - channel: nightly
      target: x86_64-pc-windows-msvc
    - channel: nightly
      target: i686-pc-windows-msvc
    - channel: stable
      target: x86_64-pc-windows-gnu
    - channel: stable
      target: i686-pc-windows-gnu
    - channel: beta
      target: x86_64-pc-windows-gnu
    - channel: beta
      target: i686-pc-windows-gnu
    - channel: nightly
      target: x86_64-pc-windows-gnu
    - channel: nightly
      target: i686-pc-windows-gnu
    - channel: 1.39.0
      target: x86_64-pc-windows-msvc
    - channel: 1.39.0
      target: i686-pc-windows-msvc
    - channel: 1.39.0
      target: x86_64-pc-windows-gnu
    - channel: 1.39.0
      target: i686-pc-windows-gnu

matrix:
  allow_failures:
    - channel: nightly

install:
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin

test_script:
  - rustc -vV
  - cargo -vV
  - cargo build
  - cargo test
  - cargo doc
  - cargo build --no-default-features
  - cargo test --no-default-features
  - cargo doc --no-default-features
  - cargo build --no-default-features --features serde
  - cargo test --no-default-features --features serde
  - cargo doc --no-default-features --features serde
  - cargo build --features serde
  - cargo test --features serde
  - cargo doc --features serde

build: false
