[package]
name = "iban_validate"
version = "0.2.1"
authors = ["Thomas den Hollander <denhollander.thomas@gmail.com>"]
include = [
    "**/*.rs",
    "Cargo.toml"
]
description = "A small crate to verify IBAN account numbers"
repository = "https://github.com/ThomasdenH/iban_check"
documentation = "https://docs.rs/iban_validate/"
license = "MIT"
readme = "README.md"
keywords = ["iban", "iban-validator"]

[badges]
travis-ci = { repository = "ThomasdenH/iban_validate" }

[lib]
name = "iban"
path = "src/lib.rs"

[dependencies]
regex = "0.2"
lazy_static = "0.2.8"
spectral = "0.6.0"
