[package]
name = "iban_validate"
version = "0.1.0"
authors = ["Thomas <denhollander.thomas@gmail.com>"]
include = [
    "**/*.rs",
    "Cargo.toml"
]

[lib]
name = "iban"
path = "src/lib.rs"

[dependencies]
regex = "0.2"
lazy_static = "0.2.8"